services:
  app:
    restart: always
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/db
      - MOUNT_PATH
      - NODE_NAME
      - IS_SESSION_MAKER
      - PARENT_NODE_URL
    ports:
      - ${PORT}:3000

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: db
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
